// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: duck_payloads.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_duck_5fpayloads_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_duck_5fpayloads_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_duck_5fpayloads_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_duck_5fpayloads_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_duck_5fpayloads_2eproto;
namespace duckcdp {
class GpsReading;
struct GpsReadingDefaultTypeInternal;
extern GpsReadingDefaultTypeInternal _GpsReading_default_instance_;
class HealthStatus;
struct HealthStatusDefaultTypeInternal;
extern HealthStatusDefaultTypeInternal _HealthStatus_default_instance_;
class MTalk;
struct MTalkDefaultTypeInternal;
extern MTalkDefaultTypeInternal _MTalk_default_instance_;
class OpText;
struct OpTextDefaultTypeInternal;
extern OpTextDefaultTypeInternal _OpText_default_instance_;
class SosAlert;
struct SosAlertDefaultTypeInternal;
extern SosAlertDefaultTypeInternal _SosAlert_default_instance_;
class StatusMsg;
struct StatusMsgDefaultTypeInternal;
extern StatusMsgDefaultTypeInternal _StatusMsg_default_instance_;
class StatusReport;
struct StatusReportDefaultTypeInternal;
extern StatusReportDefaultTypeInternal _StatusReport_default_instance_;
}  // namespace duckcdp
PROTOBUF_NAMESPACE_OPEN
template<> ::duckcdp::GpsReading* Arena::CreateMaybeMessage<::duckcdp::GpsReading>(Arena*);
template<> ::duckcdp::HealthStatus* Arena::CreateMaybeMessage<::duckcdp::HealthStatus>(Arena*);
template<> ::duckcdp::MTalk* Arena::CreateMaybeMessage<::duckcdp::MTalk>(Arena*);
template<> ::duckcdp::OpText* Arena::CreateMaybeMessage<::duckcdp::OpText>(Arena*);
template<> ::duckcdp::SosAlert* Arena::CreateMaybeMessage<::duckcdp::SosAlert>(Arena*);
template<> ::duckcdp::StatusMsg* Arena::CreateMaybeMessage<::duckcdp::StatusMsg>(Arena*);
template<> ::duckcdp::StatusReport* Arena::CreateMaybeMessage<::duckcdp::StatusReport>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace duckcdp {

enum GpsSource : int {
  GPS_SOURCE_NONE = 0,
  GPS_SOURCE_DEVICE = 1,
  GPS_SOURCE_PHONE = 2,
  GpsSource_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GpsSource_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GpsSource_IsValid(int value);
constexpr GpsSource GpsSource_MIN = GPS_SOURCE_NONE;
constexpr GpsSource GpsSource_MAX = GPS_SOURCE_PHONE;
constexpr int GpsSource_ARRAYSIZE = GpsSource_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GpsSource_descriptor();
template<typename T>
inline const std::string& GpsSource_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GpsSource>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GpsSource_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GpsSource_descriptor(), enum_t_value);
}
inline bool GpsSource_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GpsSource* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GpsSource>(
    GpsSource_descriptor(), name, value);
}
enum GpsNoFixReason : int {
  GPS_REASON_NONE = 0,
  GPS_REASON_NO_SIGNAL = 1,
  GPS_REASON_NO_RESPONSE = 2,
  GpsNoFixReason_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GpsNoFixReason_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GpsNoFixReason_IsValid(int value);
constexpr GpsNoFixReason GpsNoFixReason_MIN = GPS_REASON_NONE;
constexpr GpsNoFixReason GpsNoFixReason_MAX = GPS_REASON_NO_RESPONSE;
constexpr int GpsNoFixReason_ARRAYSIZE = GpsNoFixReason_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GpsNoFixReason_descriptor();
template<typename T>
inline const std::string& GpsNoFixReason_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GpsNoFixReason>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GpsNoFixReason_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GpsNoFixReason_descriptor(), enum_t_value);
}
inline bool GpsNoFixReason_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GpsNoFixReason* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GpsNoFixReason>(
    GpsNoFixReason_descriptor(), name, value);
}
enum SosOrigin : int {
  SOS_ORIGIN_UNKNOWN = 0,
  SOS_ORIGIN_DEVICE = 1,
  SOS_ORIGIN_PHONE = 2,
  SosOrigin_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SosOrigin_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SosOrigin_IsValid(int value);
constexpr SosOrigin SosOrigin_MIN = SOS_ORIGIN_UNKNOWN;
constexpr SosOrigin SosOrigin_MAX = SOS_ORIGIN_PHONE;
constexpr int SosOrigin_ARRAYSIZE = SosOrigin_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SosOrigin_descriptor();
template<typename T>
inline const std::string& SosOrigin_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SosOrigin>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SosOrigin_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SosOrigin_descriptor(), enum_t_value);
}
inline bool SosOrigin_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SosOrigin* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SosOrigin>(
    SosOrigin_descriptor(), name, value);
}
enum MTalkKind : int {
  MTALK_MSG = 0,
  MTALK_ACK = 1,
  MTalkKind_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MTalkKind_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MTalkKind_IsValid(int value);
constexpr MTalkKind MTalkKind_MIN = MTALK_MSG;
constexpr MTalkKind MTalkKind_MAX = MTALK_ACK;
constexpr int MTalkKind_ARRAYSIZE = MTalkKind_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MTalkKind_descriptor();
template<typename T>
inline const std::string& MTalkKind_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MTalkKind>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MTalkKind_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MTalkKind_descriptor(), enum_t_value);
}
inline bool MTalkKind_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MTalkKind* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MTalkKind>(
    MTalkKind_descriptor(), name, value);
}
enum StatusMsgSrc : int {
  STATUS_MSG_SRC_UNKNOWN = 0,
  STATUS_MSG_SRC_PHONE = 1,
  STATUS_MSG_SRC_DEVICE = 2,
  StatusMsgSrc_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  StatusMsgSrc_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool StatusMsgSrc_IsValid(int value);
constexpr StatusMsgSrc StatusMsgSrc_MIN = STATUS_MSG_SRC_UNKNOWN;
constexpr StatusMsgSrc StatusMsgSrc_MAX = STATUS_MSG_SRC_DEVICE;
constexpr int StatusMsgSrc_ARRAYSIZE = StatusMsgSrc_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StatusMsgSrc_descriptor();
template<typename T>
inline const std::string& StatusMsgSrc_Name(T enum_t_value) {
  static_assert(::std::is_same<T, StatusMsgSrc>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function StatusMsgSrc_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    StatusMsgSrc_descriptor(), enum_t_value);
}
inline bool StatusMsgSrc_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, StatusMsgSrc* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<StatusMsgSrc>(
    StatusMsgSrc_descriptor(), name, value);
}
// ===================================================================

class GpsReading final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:duckcdp.GpsReading) */ {
 public:
  inline GpsReading() : GpsReading(nullptr) {}
  ~GpsReading() override;
  explicit PROTOBUF_CONSTEXPR GpsReading(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GpsReading(const GpsReading& from);
  GpsReading(GpsReading&& from) noexcept
    : GpsReading() {
    *this = ::std::move(from);
  }

  inline GpsReading& operator=(const GpsReading& from) {
    CopyFrom(from);
    return *this;
  }
  inline GpsReading& operator=(GpsReading&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GpsReading& default_instance() {
    return *internal_default_instance();
  }
  static inline const GpsReading* internal_default_instance() {
    return reinterpret_cast<const GpsReading*>(
               &_GpsReading_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GpsReading& a, GpsReading& b) {
    a.Swap(&b);
  }
  inline void Swap(GpsReading* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GpsReading* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GpsReading* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GpsReading>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GpsReading& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GpsReading& from) {
    GpsReading::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GpsReading* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "duckcdp.GpsReading";
  }
  protected:
  explicit GpsReading(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHasFixFieldNumber = 1,
    kSourceFieldNumber = 2,
    kNoFixReasonFieldNumber = 3,
    kLatE7FieldNumber = 4,
    kLngE7FieldNumber = 5,
    kAltMFieldNumber = 6,
    kSpdDkmhFieldNumber = 7,
    kHdgDegFieldNumber = 8,
    kSatsFieldNumber = 9,
    kBattPctFieldNumber = 10,
  };
  // bool has_fix = 1;
  void clear_has_fix();
  bool has_fix() const;
  void set_has_fix(bool value);
  private:
  bool _internal_has_fix() const;
  void _internal_set_has_fix(bool value);
  public:

  // .duckcdp.GpsSource source = 2;
  void clear_source();
  ::duckcdp::GpsSource source() const;
  void set_source(::duckcdp::GpsSource value);
  private:
  ::duckcdp::GpsSource _internal_source() const;
  void _internal_set_source(::duckcdp::GpsSource value);
  public:

  // .duckcdp.GpsNoFixReason no_fix_reason = 3;
  void clear_no_fix_reason();
  ::duckcdp::GpsNoFixReason no_fix_reason() const;
  void set_no_fix_reason(::duckcdp::GpsNoFixReason value);
  private:
  ::duckcdp::GpsNoFixReason _internal_no_fix_reason() const;
  void _internal_set_no_fix_reason(::duckcdp::GpsNoFixReason value);
  public:

  // sint32 lat_e7 = 4;
  void clear_lat_e7();
  int32_t lat_e7() const;
  void set_lat_e7(int32_t value);
  private:
  int32_t _internal_lat_e7() const;
  void _internal_set_lat_e7(int32_t value);
  public:

  // sint32 lng_e7 = 5;
  void clear_lng_e7();
  int32_t lng_e7() const;
  void set_lng_e7(int32_t value);
  private:
  int32_t _internal_lng_e7() const;
  void _internal_set_lng_e7(int32_t value);
  public:

  // sint32 alt_m = 6;
  void clear_alt_m();
  int32_t alt_m() const;
  void set_alt_m(int32_t value);
  private:
  int32_t _internal_alt_m() const;
  void _internal_set_alt_m(int32_t value);
  public:

  // uint32 spd_dkmh = 7;
  void clear_spd_dkmh();
  uint32_t spd_dkmh() const;
  void set_spd_dkmh(uint32_t value);
  private:
  uint32_t _internal_spd_dkmh() const;
  void _internal_set_spd_dkmh(uint32_t value);
  public:

  // uint32 hdg_deg = 8;
  void clear_hdg_deg();
  uint32_t hdg_deg() const;
  void set_hdg_deg(uint32_t value);
  private:
  uint32_t _internal_hdg_deg() const;
  void _internal_set_hdg_deg(uint32_t value);
  public:

  // uint32 sats = 9;
  void clear_sats();
  uint32_t sats() const;
  void set_sats(uint32_t value);
  private:
  uint32_t _internal_sats() const;
  void _internal_set_sats(uint32_t value);
  public:

  // uint32 batt_pct = 10;
  void clear_batt_pct();
  uint32_t batt_pct() const;
  void set_batt_pct(uint32_t value);
  private:
  uint32_t _internal_batt_pct() const;
  void _internal_set_batt_pct(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:duckcdp.GpsReading)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool has_fix_;
    int source_;
    int no_fix_reason_;
    int32_t lat_e7_;
    int32_t lng_e7_;
    int32_t alt_m_;
    uint32_t spd_dkmh_;
    uint32_t hdg_deg_;
    uint32_t sats_;
    uint32_t batt_pct_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_duck_5fpayloads_2eproto;
};
// -------------------------------------------------------------------

class SosAlert final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:duckcdp.SosAlert) */ {
 public:
  inline SosAlert() : SosAlert(nullptr) {}
  ~SosAlert() override;
  explicit PROTOBUF_CONSTEXPR SosAlert(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SosAlert(const SosAlert& from);
  SosAlert(SosAlert&& from) noexcept
    : SosAlert() {
    *this = ::std::move(from);
  }

  inline SosAlert& operator=(const SosAlert& from) {
    CopyFrom(from);
    return *this;
  }
  inline SosAlert& operator=(SosAlert&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SosAlert& default_instance() {
    return *internal_default_instance();
  }
  static inline const SosAlert* internal_default_instance() {
    return reinterpret_cast<const SosAlert*>(
               &_SosAlert_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SosAlert& a, SosAlert& b) {
    a.Swap(&b);
  }
  inline void Swap(SosAlert* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SosAlert* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SosAlert* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SosAlert>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SosAlert& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SosAlert& from) {
    SosAlert::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SosAlert* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "duckcdp.SosAlert";
  }
  protected:
  explicit SosAlert(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOriginFieldNumber = 1,
    kGpsSourceFieldNumber = 2,
    kHasGpsFieldNumber = 3,
    kLatE7FieldNumber = 4,
    kLngE7FieldNumber = 5,
    kAltMFieldNumber = 6,
    kSpdDkmhFieldNumber = 7,
    kHdgDegFieldNumber = 8,
    kBattPctFieldNumber = 9,
  };
  // .duckcdp.SosOrigin origin = 1;
  void clear_origin();
  ::duckcdp::SosOrigin origin() const;
  void set_origin(::duckcdp::SosOrigin value);
  private:
  ::duckcdp::SosOrigin _internal_origin() const;
  void _internal_set_origin(::duckcdp::SosOrigin value);
  public:

  // .duckcdp.GpsSource gps_source = 2;
  void clear_gps_source();
  ::duckcdp::GpsSource gps_source() const;
  void set_gps_source(::duckcdp::GpsSource value);
  private:
  ::duckcdp::GpsSource _internal_gps_source() const;
  void _internal_set_gps_source(::duckcdp::GpsSource value);
  public:

  // bool has_gps = 3;
  void clear_has_gps();
  bool has_gps() const;
  void set_has_gps(bool value);
  private:
  bool _internal_has_gps() const;
  void _internal_set_has_gps(bool value);
  public:

  // sint32 lat_e7 = 4;
  void clear_lat_e7();
  int32_t lat_e7() const;
  void set_lat_e7(int32_t value);
  private:
  int32_t _internal_lat_e7() const;
  void _internal_set_lat_e7(int32_t value);
  public:

  // sint32 lng_e7 = 5;
  void clear_lng_e7();
  int32_t lng_e7() const;
  void set_lng_e7(int32_t value);
  private:
  int32_t _internal_lng_e7() const;
  void _internal_set_lng_e7(int32_t value);
  public:

  // sint32 alt_m = 6;
  void clear_alt_m();
  int32_t alt_m() const;
  void set_alt_m(int32_t value);
  private:
  int32_t _internal_alt_m() const;
  void _internal_set_alt_m(int32_t value);
  public:

  // uint32 spd_dkmh = 7;
  void clear_spd_dkmh();
  uint32_t spd_dkmh() const;
  void set_spd_dkmh(uint32_t value);
  private:
  uint32_t _internal_spd_dkmh() const;
  void _internal_set_spd_dkmh(uint32_t value);
  public:

  // uint32 hdg_deg = 8;
  void clear_hdg_deg();
  uint32_t hdg_deg() const;
  void set_hdg_deg(uint32_t value);
  private:
  uint32_t _internal_hdg_deg() const;
  void _internal_set_hdg_deg(uint32_t value);
  public:

  // uint32 batt_pct = 9;
  void clear_batt_pct();
  uint32_t batt_pct() const;
  void set_batt_pct(uint32_t value);
  private:
  uint32_t _internal_batt_pct() const;
  void _internal_set_batt_pct(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:duckcdp.SosAlert)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int origin_;
    int gps_source_;
    bool has_gps_;
    int32_t lat_e7_;
    int32_t lng_e7_;
    int32_t alt_m_;
    uint32_t spd_dkmh_;
    uint32_t hdg_deg_;
    uint32_t batt_pct_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_duck_5fpayloads_2eproto;
};
// -------------------------------------------------------------------

class HealthStatus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:duckcdp.HealthStatus) */ {
 public:
  inline HealthStatus() : HealthStatus(nullptr) {}
  ~HealthStatus() override;
  explicit PROTOBUF_CONSTEXPR HealthStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HealthStatus(const HealthStatus& from);
  HealthStatus(HealthStatus&& from) noexcept
    : HealthStatus() {
    *this = ::std::move(from);
  }

  inline HealthStatus& operator=(const HealthStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline HealthStatus& operator=(HealthStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HealthStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const HealthStatus* internal_default_instance() {
    return reinterpret_cast<const HealthStatus*>(
               &_HealthStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(HealthStatus& a, HealthStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(HealthStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HealthStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HealthStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HealthStatus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HealthStatus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HealthStatus& from) {
    HealthStatus::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HealthStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "duckcdp.HealthStatus";
  }
  protected:
  explicit HealthStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCounterFieldNumber = 1,
    kFreeMemoryFieldNumber = 2,
  };
  // uint32 counter = 1;
  void clear_counter();
  uint32_t counter() const;
  void set_counter(uint32_t value);
  private:
  uint32_t _internal_counter() const;
  void _internal_set_counter(uint32_t value);
  public:

  // int32 free_memory = 2;
  void clear_free_memory();
  int32_t free_memory() const;
  void set_free_memory(int32_t value);
  private:
  int32_t _internal_free_memory() const;
  void _internal_set_free_memory(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:duckcdp.HealthStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t counter_;
    int32_t free_memory_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_duck_5fpayloads_2eproto;
};
// -------------------------------------------------------------------

class MTalk final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:duckcdp.MTalk) */ {
 public:
  inline MTalk() : MTalk(nullptr) {}
  ~MTalk() override;
  explicit PROTOBUF_CONSTEXPR MTalk(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MTalk(const MTalk& from);
  MTalk(MTalk&& from) noexcept
    : MTalk() {
    *this = ::std::move(from);
  }

  inline MTalk& operator=(const MTalk& from) {
    CopyFrom(from);
    return *this;
  }
  inline MTalk& operator=(MTalk&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MTalk& default_instance() {
    return *internal_default_instance();
  }
  static inline const MTalk* internal_default_instance() {
    return reinterpret_cast<const MTalk*>(
               &_MTalk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MTalk& a, MTalk& b) {
    a.Swap(&b);
  }
  inline void Swap(MTalk* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MTalk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MTalk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MTalk>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MTalk& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MTalk& from) {
    MTalk::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MTalk* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "duckcdp.MTalk";
  }
  protected:
  explicit MTalk(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMidFieldNumber = 2,
    kTextFieldNumber = 3,
    kKindFieldNumber = 1,
  };
  // string mid = 2;
  void clear_mid();
  const std::string& mid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mid();
  PROTOBUF_NODISCARD std::string* release_mid();
  void set_allocated_mid(std::string* mid);
  private:
  const std::string& _internal_mid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mid(const std::string& value);
  std::string* _internal_mutable_mid();
  public:

  // string text = 3;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // .duckcdp.MTalkKind kind = 1;
  void clear_kind();
  ::duckcdp::MTalkKind kind() const;
  void set_kind(::duckcdp::MTalkKind value);
  private:
  ::duckcdp::MTalkKind _internal_kind() const;
  void _internal_set_kind(::duckcdp::MTalkKind value);
  public:

  // @@protoc_insertion_point(class_scope:duckcdp.MTalk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    int kind_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_duck_5fpayloads_2eproto;
};
// -------------------------------------------------------------------

class StatusMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:duckcdp.StatusMsg) */ {
 public:
  inline StatusMsg() : StatusMsg(nullptr) {}
  ~StatusMsg() override;
  explicit PROTOBUF_CONSTEXPR StatusMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StatusMsg(const StatusMsg& from);
  StatusMsg(StatusMsg&& from) noexcept
    : StatusMsg() {
    *this = ::std::move(from);
  }

  inline StatusMsg& operator=(const StatusMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusMsg& operator=(StatusMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StatusMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const StatusMsg* internal_default_instance() {
    return reinterpret_cast<const StatusMsg*>(
               &_StatusMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StatusMsg& a, StatusMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(StatusMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatusMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StatusMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StatusMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StatusMsg& from) {
    StatusMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "duckcdp.StatusMsg";
  }
  protected:
  explicit StatusMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUrgencyFieldNumber = 2,
    kTextFieldNumber = 6,
    kSrcFieldNumber = 1,
    kHasGpsFieldNumber = 3,
    kLatE7FieldNumber = 4,
    kLngE7FieldNumber = 5,
  };
  // string urgency = 2;
  void clear_urgency();
  const std::string& urgency() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_urgency(ArgT0&& arg0, ArgT... args);
  std::string* mutable_urgency();
  PROTOBUF_NODISCARD std::string* release_urgency();
  void set_allocated_urgency(std::string* urgency);
  private:
  const std::string& _internal_urgency() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_urgency(const std::string& value);
  std::string* _internal_mutable_urgency();
  public:

  // string text = 6;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // .duckcdp.StatusMsgSrc src = 1;
  void clear_src();
  ::duckcdp::StatusMsgSrc src() const;
  void set_src(::duckcdp::StatusMsgSrc value);
  private:
  ::duckcdp::StatusMsgSrc _internal_src() const;
  void _internal_set_src(::duckcdp::StatusMsgSrc value);
  public:

  // bool has_gps = 3;
  void clear_has_gps();
  bool has_gps() const;
  void set_has_gps(bool value);
  private:
  bool _internal_has_gps() const;
  void _internal_set_has_gps(bool value);
  public:

  // sint32 lat_e7 = 4;
  void clear_lat_e7();
  int32_t lat_e7() const;
  void set_lat_e7(int32_t value);
  private:
  int32_t _internal_lat_e7() const;
  void _internal_set_lat_e7(int32_t value);
  public:

  // sint32 lng_e7 = 5;
  void clear_lng_e7();
  int32_t lng_e7() const;
  void set_lng_e7(int32_t value);
  private:
  int32_t _internal_lng_e7() const;
  void _internal_set_lng_e7(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:duckcdp.StatusMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr urgency_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    int src_;
    bool has_gps_;
    int32_t lat_e7_;
    int32_t lng_e7_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_duck_5fpayloads_2eproto;
};
// -------------------------------------------------------------------

class StatusReport final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:duckcdp.StatusReport) */ {
 public:
  inline StatusReport() : StatusReport(nullptr) {}
  ~StatusReport() override;
  explicit PROTOBUF_CONSTEXPR StatusReport(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StatusReport(const StatusReport& from);
  StatusReport(StatusReport&& from) noexcept
    : StatusReport() {
    *this = ::std::move(from);
  }

  inline StatusReport& operator=(const StatusReport& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatusReport& operator=(StatusReport&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StatusReport& default_instance() {
    return *internal_default_instance();
  }
  enum ReportCase {
    kSos = 1,
    kMsg = 2,
    REPORT_NOT_SET = 0,
  };

  static inline const StatusReport* internal_default_instance() {
    return reinterpret_cast<const StatusReport*>(
               &_StatusReport_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(StatusReport& a, StatusReport& b) {
    a.Swap(&b);
  }
  inline void Swap(StatusReport* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatusReport* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatusReport* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StatusReport>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StatusReport& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StatusReport& from) {
    StatusReport::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatusReport* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "duckcdp.StatusReport";
  }
  protected:
  explicit StatusReport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSosFieldNumber = 1,
    kMsgFieldNumber = 2,
  };
  // .duckcdp.SosAlert sos = 1;
  bool has_sos() const;
  private:
  bool _internal_has_sos() const;
  public:
  void clear_sos();
  const ::duckcdp::SosAlert& sos() const;
  PROTOBUF_NODISCARD ::duckcdp::SosAlert* release_sos();
  ::duckcdp::SosAlert* mutable_sos();
  void set_allocated_sos(::duckcdp::SosAlert* sos);
  private:
  const ::duckcdp::SosAlert& _internal_sos() const;
  ::duckcdp::SosAlert* _internal_mutable_sos();
  public:
  void unsafe_arena_set_allocated_sos(
      ::duckcdp::SosAlert* sos);
  ::duckcdp::SosAlert* unsafe_arena_release_sos();

  // .duckcdp.StatusMsg msg = 2;
  bool has_msg() const;
  private:
  bool _internal_has_msg() const;
  public:
  void clear_msg();
  const ::duckcdp::StatusMsg& msg() const;
  PROTOBUF_NODISCARD ::duckcdp::StatusMsg* release_msg();
  ::duckcdp::StatusMsg* mutable_msg();
  void set_allocated_msg(::duckcdp::StatusMsg* msg);
  private:
  const ::duckcdp::StatusMsg& _internal_msg() const;
  ::duckcdp::StatusMsg* _internal_mutable_msg();
  public:
  void unsafe_arena_set_allocated_msg(
      ::duckcdp::StatusMsg* msg);
  ::duckcdp::StatusMsg* unsafe_arena_release_msg();

  void clear_report();
  ReportCase report_case() const;
  // @@protoc_insertion_point(class_scope:duckcdp.StatusReport)
 private:
  class _Internal;
  void set_has_sos();
  void set_has_msg();

  inline bool has_report() const;
  inline void clear_has_report();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ReportUnion {
      constexpr ReportUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::duckcdp::SosAlert* sos_;
      ::duckcdp::StatusMsg* msg_;
    } report_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_duck_5fpayloads_2eproto;
};
// -------------------------------------------------------------------

class OpText final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:duckcdp.OpText) */ {
 public:
  inline OpText() : OpText(nullptr) {}
  ~OpText() override;
  explicit PROTOBUF_CONSTEXPR OpText(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OpText(const OpText& from);
  OpText(OpText&& from) noexcept
    : OpText() {
    *this = ::std::move(from);
  }

  inline OpText& operator=(const OpText& from) {
    CopyFrom(from);
    return *this;
  }
  inline OpText& operator=(OpText&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OpText& default_instance() {
    return *internal_default_instance();
  }
  static inline const OpText* internal_default_instance() {
    return reinterpret_cast<const OpText*>(
               &_OpText_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(OpText& a, OpText& b) {
    a.Swap(&b);
  }
  inline void Swap(OpText* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OpText* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OpText* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OpText>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OpText& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OpText& from) {
    OpText::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OpText* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "duckcdp.OpText";
  }
  protected:
  explicit OpText(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 1,
  };
  // string text = 1;
  void clear_text();
  const std::string& text() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_text(ArgT0&& arg0, ArgT... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // @@protoc_insertion_point(class_scope:duckcdp.OpText)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_duck_5fpayloads_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GpsReading

// bool has_fix = 1;
inline void GpsReading::clear_has_fix() {
  _impl_.has_fix_ = false;
}
inline bool GpsReading::_internal_has_fix() const {
  return _impl_.has_fix_;
}
inline bool GpsReading::has_fix() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.has_fix)
  return _internal_has_fix();
}
inline void GpsReading::_internal_set_has_fix(bool value) {
  
  _impl_.has_fix_ = value;
}
inline void GpsReading::set_has_fix(bool value) {
  _internal_set_has_fix(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.has_fix)
}

// .duckcdp.GpsSource source = 2;
inline void GpsReading::clear_source() {
  _impl_.source_ = 0;
}
inline ::duckcdp::GpsSource GpsReading::_internal_source() const {
  return static_cast< ::duckcdp::GpsSource >(_impl_.source_);
}
inline ::duckcdp::GpsSource GpsReading::source() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.source)
  return _internal_source();
}
inline void GpsReading::_internal_set_source(::duckcdp::GpsSource value) {
  
  _impl_.source_ = value;
}
inline void GpsReading::set_source(::duckcdp::GpsSource value) {
  _internal_set_source(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.source)
}

// .duckcdp.GpsNoFixReason no_fix_reason = 3;
inline void GpsReading::clear_no_fix_reason() {
  _impl_.no_fix_reason_ = 0;
}
inline ::duckcdp::GpsNoFixReason GpsReading::_internal_no_fix_reason() const {
  return static_cast< ::duckcdp::GpsNoFixReason >(_impl_.no_fix_reason_);
}
inline ::duckcdp::GpsNoFixReason GpsReading::no_fix_reason() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.no_fix_reason)
  return _internal_no_fix_reason();
}
inline void GpsReading::_internal_set_no_fix_reason(::duckcdp::GpsNoFixReason value) {
  
  _impl_.no_fix_reason_ = value;
}
inline void GpsReading::set_no_fix_reason(::duckcdp::GpsNoFixReason value) {
  _internal_set_no_fix_reason(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.no_fix_reason)
}

// sint32 lat_e7 = 4;
inline void GpsReading::clear_lat_e7() {
  _impl_.lat_e7_ = 0;
}
inline int32_t GpsReading::_internal_lat_e7() const {
  return _impl_.lat_e7_;
}
inline int32_t GpsReading::lat_e7() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.lat_e7)
  return _internal_lat_e7();
}
inline void GpsReading::_internal_set_lat_e7(int32_t value) {
  
  _impl_.lat_e7_ = value;
}
inline void GpsReading::set_lat_e7(int32_t value) {
  _internal_set_lat_e7(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.lat_e7)
}

// sint32 lng_e7 = 5;
inline void GpsReading::clear_lng_e7() {
  _impl_.lng_e7_ = 0;
}
inline int32_t GpsReading::_internal_lng_e7() const {
  return _impl_.lng_e7_;
}
inline int32_t GpsReading::lng_e7() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.lng_e7)
  return _internal_lng_e7();
}
inline void GpsReading::_internal_set_lng_e7(int32_t value) {
  
  _impl_.lng_e7_ = value;
}
inline void GpsReading::set_lng_e7(int32_t value) {
  _internal_set_lng_e7(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.lng_e7)
}

// sint32 alt_m = 6;
inline void GpsReading::clear_alt_m() {
  _impl_.alt_m_ = 0;
}
inline int32_t GpsReading::_internal_alt_m() const {
  return _impl_.alt_m_;
}
inline int32_t GpsReading::alt_m() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.alt_m)
  return _internal_alt_m();
}
inline void GpsReading::_internal_set_alt_m(int32_t value) {
  
  _impl_.alt_m_ = value;
}
inline void GpsReading::set_alt_m(int32_t value) {
  _internal_set_alt_m(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.alt_m)
}

// uint32 spd_dkmh = 7;
inline void GpsReading::clear_spd_dkmh() {
  _impl_.spd_dkmh_ = 0u;
}
inline uint32_t GpsReading::_internal_spd_dkmh() const {
  return _impl_.spd_dkmh_;
}
inline uint32_t GpsReading::spd_dkmh() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.spd_dkmh)
  return _internal_spd_dkmh();
}
inline void GpsReading::_internal_set_spd_dkmh(uint32_t value) {
  
  _impl_.spd_dkmh_ = value;
}
inline void GpsReading::set_spd_dkmh(uint32_t value) {
  _internal_set_spd_dkmh(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.spd_dkmh)
}

// uint32 hdg_deg = 8;
inline void GpsReading::clear_hdg_deg() {
  _impl_.hdg_deg_ = 0u;
}
inline uint32_t GpsReading::_internal_hdg_deg() const {
  return _impl_.hdg_deg_;
}
inline uint32_t GpsReading::hdg_deg() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.hdg_deg)
  return _internal_hdg_deg();
}
inline void GpsReading::_internal_set_hdg_deg(uint32_t value) {
  
  _impl_.hdg_deg_ = value;
}
inline void GpsReading::set_hdg_deg(uint32_t value) {
  _internal_set_hdg_deg(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.hdg_deg)
}

// uint32 sats = 9;
inline void GpsReading::clear_sats() {
  _impl_.sats_ = 0u;
}
inline uint32_t GpsReading::_internal_sats() const {
  return _impl_.sats_;
}
inline uint32_t GpsReading::sats() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.sats)
  return _internal_sats();
}
inline void GpsReading::_internal_set_sats(uint32_t value) {
  
  _impl_.sats_ = value;
}
inline void GpsReading::set_sats(uint32_t value) {
  _internal_set_sats(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.sats)
}

// uint32 batt_pct = 10;
inline void GpsReading::clear_batt_pct() {
  _impl_.batt_pct_ = 0u;
}
inline uint32_t GpsReading::_internal_batt_pct() const {
  return _impl_.batt_pct_;
}
inline uint32_t GpsReading::batt_pct() const {
  // @@protoc_insertion_point(field_get:duckcdp.GpsReading.batt_pct)
  return _internal_batt_pct();
}
inline void GpsReading::_internal_set_batt_pct(uint32_t value) {
  
  _impl_.batt_pct_ = value;
}
inline void GpsReading::set_batt_pct(uint32_t value) {
  _internal_set_batt_pct(value);
  // @@protoc_insertion_point(field_set:duckcdp.GpsReading.batt_pct)
}

// -------------------------------------------------------------------

// SosAlert

// .duckcdp.SosOrigin origin = 1;
inline void SosAlert::clear_origin() {
  _impl_.origin_ = 0;
}
inline ::duckcdp::SosOrigin SosAlert::_internal_origin() const {
  return static_cast< ::duckcdp::SosOrigin >(_impl_.origin_);
}
inline ::duckcdp::SosOrigin SosAlert::origin() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.origin)
  return _internal_origin();
}
inline void SosAlert::_internal_set_origin(::duckcdp::SosOrigin value) {
  
  _impl_.origin_ = value;
}
inline void SosAlert::set_origin(::duckcdp::SosOrigin value) {
  _internal_set_origin(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.origin)
}

// .duckcdp.GpsSource gps_source = 2;
inline void SosAlert::clear_gps_source() {
  _impl_.gps_source_ = 0;
}
inline ::duckcdp::GpsSource SosAlert::_internal_gps_source() const {
  return static_cast< ::duckcdp::GpsSource >(_impl_.gps_source_);
}
inline ::duckcdp::GpsSource SosAlert::gps_source() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.gps_source)
  return _internal_gps_source();
}
inline void SosAlert::_internal_set_gps_source(::duckcdp::GpsSource value) {
  
  _impl_.gps_source_ = value;
}
inline void SosAlert::set_gps_source(::duckcdp::GpsSource value) {
  _internal_set_gps_source(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.gps_source)
}

// bool has_gps = 3;
inline void SosAlert::clear_has_gps() {
  _impl_.has_gps_ = false;
}
inline bool SosAlert::_internal_has_gps() const {
  return _impl_.has_gps_;
}
inline bool SosAlert::has_gps() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.has_gps)
  return _internal_has_gps();
}
inline void SosAlert::_internal_set_has_gps(bool value) {
  
  _impl_.has_gps_ = value;
}
inline void SosAlert::set_has_gps(bool value) {
  _internal_set_has_gps(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.has_gps)
}

// sint32 lat_e7 = 4;
inline void SosAlert::clear_lat_e7() {
  _impl_.lat_e7_ = 0;
}
inline int32_t SosAlert::_internal_lat_e7() const {
  return _impl_.lat_e7_;
}
inline int32_t SosAlert::lat_e7() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.lat_e7)
  return _internal_lat_e7();
}
inline void SosAlert::_internal_set_lat_e7(int32_t value) {
  
  _impl_.lat_e7_ = value;
}
inline void SosAlert::set_lat_e7(int32_t value) {
  _internal_set_lat_e7(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.lat_e7)
}

// sint32 lng_e7 = 5;
inline void SosAlert::clear_lng_e7() {
  _impl_.lng_e7_ = 0;
}
inline int32_t SosAlert::_internal_lng_e7() const {
  return _impl_.lng_e7_;
}
inline int32_t SosAlert::lng_e7() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.lng_e7)
  return _internal_lng_e7();
}
inline void SosAlert::_internal_set_lng_e7(int32_t value) {
  
  _impl_.lng_e7_ = value;
}
inline void SosAlert::set_lng_e7(int32_t value) {
  _internal_set_lng_e7(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.lng_e7)
}

// sint32 alt_m = 6;
inline void SosAlert::clear_alt_m() {
  _impl_.alt_m_ = 0;
}
inline int32_t SosAlert::_internal_alt_m() const {
  return _impl_.alt_m_;
}
inline int32_t SosAlert::alt_m() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.alt_m)
  return _internal_alt_m();
}
inline void SosAlert::_internal_set_alt_m(int32_t value) {
  
  _impl_.alt_m_ = value;
}
inline void SosAlert::set_alt_m(int32_t value) {
  _internal_set_alt_m(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.alt_m)
}

// uint32 spd_dkmh = 7;
inline void SosAlert::clear_spd_dkmh() {
  _impl_.spd_dkmh_ = 0u;
}
inline uint32_t SosAlert::_internal_spd_dkmh() const {
  return _impl_.spd_dkmh_;
}
inline uint32_t SosAlert::spd_dkmh() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.spd_dkmh)
  return _internal_spd_dkmh();
}
inline void SosAlert::_internal_set_spd_dkmh(uint32_t value) {
  
  _impl_.spd_dkmh_ = value;
}
inline void SosAlert::set_spd_dkmh(uint32_t value) {
  _internal_set_spd_dkmh(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.spd_dkmh)
}

// uint32 hdg_deg = 8;
inline void SosAlert::clear_hdg_deg() {
  _impl_.hdg_deg_ = 0u;
}
inline uint32_t SosAlert::_internal_hdg_deg() const {
  return _impl_.hdg_deg_;
}
inline uint32_t SosAlert::hdg_deg() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.hdg_deg)
  return _internal_hdg_deg();
}
inline void SosAlert::_internal_set_hdg_deg(uint32_t value) {
  
  _impl_.hdg_deg_ = value;
}
inline void SosAlert::set_hdg_deg(uint32_t value) {
  _internal_set_hdg_deg(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.hdg_deg)
}

// uint32 batt_pct = 9;
inline void SosAlert::clear_batt_pct() {
  _impl_.batt_pct_ = 0u;
}
inline uint32_t SosAlert::_internal_batt_pct() const {
  return _impl_.batt_pct_;
}
inline uint32_t SosAlert::batt_pct() const {
  // @@protoc_insertion_point(field_get:duckcdp.SosAlert.batt_pct)
  return _internal_batt_pct();
}
inline void SosAlert::_internal_set_batt_pct(uint32_t value) {
  
  _impl_.batt_pct_ = value;
}
inline void SosAlert::set_batt_pct(uint32_t value) {
  _internal_set_batt_pct(value);
  // @@protoc_insertion_point(field_set:duckcdp.SosAlert.batt_pct)
}

// -------------------------------------------------------------------

// HealthStatus

// uint32 counter = 1;
inline void HealthStatus::clear_counter() {
  _impl_.counter_ = 0u;
}
inline uint32_t HealthStatus::_internal_counter() const {
  return _impl_.counter_;
}
inline uint32_t HealthStatus::counter() const {
  // @@protoc_insertion_point(field_get:duckcdp.HealthStatus.counter)
  return _internal_counter();
}
inline void HealthStatus::_internal_set_counter(uint32_t value) {
  
  _impl_.counter_ = value;
}
inline void HealthStatus::set_counter(uint32_t value) {
  _internal_set_counter(value);
  // @@protoc_insertion_point(field_set:duckcdp.HealthStatus.counter)
}

// int32 free_memory = 2;
inline void HealthStatus::clear_free_memory() {
  _impl_.free_memory_ = 0;
}
inline int32_t HealthStatus::_internal_free_memory() const {
  return _impl_.free_memory_;
}
inline int32_t HealthStatus::free_memory() const {
  // @@protoc_insertion_point(field_get:duckcdp.HealthStatus.free_memory)
  return _internal_free_memory();
}
inline void HealthStatus::_internal_set_free_memory(int32_t value) {
  
  _impl_.free_memory_ = value;
}
inline void HealthStatus::set_free_memory(int32_t value) {
  _internal_set_free_memory(value);
  // @@protoc_insertion_point(field_set:duckcdp.HealthStatus.free_memory)
}

// -------------------------------------------------------------------

// MTalk

// .duckcdp.MTalkKind kind = 1;
inline void MTalk::clear_kind() {
  _impl_.kind_ = 0;
}
inline ::duckcdp::MTalkKind MTalk::_internal_kind() const {
  return static_cast< ::duckcdp::MTalkKind >(_impl_.kind_);
}
inline ::duckcdp::MTalkKind MTalk::kind() const {
  // @@protoc_insertion_point(field_get:duckcdp.MTalk.kind)
  return _internal_kind();
}
inline void MTalk::_internal_set_kind(::duckcdp::MTalkKind value) {
  
  _impl_.kind_ = value;
}
inline void MTalk::set_kind(::duckcdp::MTalkKind value) {
  _internal_set_kind(value);
  // @@protoc_insertion_point(field_set:duckcdp.MTalk.kind)
}

// string mid = 2;
inline void MTalk::clear_mid() {
  _impl_.mid_.ClearToEmpty();
}
inline const std::string& MTalk::mid() const {
  // @@protoc_insertion_point(field_get:duckcdp.MTalk.mid)
  return _internal_mid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MTalk::set_mid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.mid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:duckcdp.MTalk.mid)
}
inline std::string* MTalk::mutable_mid() {
  std::string* _s = _internal_mutable_mid();
  // @@protoc_insertion_point(field_mutable:duckcdp.MTalk.mid)
  return _s;
}
inline const std::string& MTalk::_internal_mid() const {
  return _impl_.mid_.Get();
}
inline void MTalk::_internal_set_mid(const std::string& value) {
  
  _impl_.mid_.Set(value, GetArenaForAllocation());
}
inline std::string* MTalk::_internal_mutable_mid() {
  
  return _impl_.mid_.Mutable(GetArenaForAllocation());
}
inline std::string* MTalk::release_mid() {
  // @@protoc_insertion_point(field_release:duckcdp.MTalk.mid)
  return _impl_.mid_.Release();
}
inline void MTalk::set_allocated_mid(std::string* mid) {
  if (mid != nullptr) {
    
  } else {
    
  }
  _impl_.mid_.SetAllocated(mid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.mid_.IsDefault()) {
    _impl_.mid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:duckcdp.MTalk.mid)
}

// string text = 3;
inline void MTalk::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& MTalk::text() const {
  // @@protoc_insertion_point(field_get:duckcdp.MTalk.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MTalk::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:duckcdp.MTalk.text)
}
inline std::string* MTalk::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:duckcdp.MTalk.text)
  return _s;
}
inline const std::string& MTalk::_internal_text() const {
  return _impl_.text_.Get();
}
inline void MTalk::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* MTalk::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* MTalk::release_text() {
  // @@protoc_insertion_point(field_release:duckcdp.MTalk.text)
  return _impl_.text_.Release();
}
inline void MTalk::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:duckcdp.MTalk.text)
}

// -------------------------------------------------------------------

// StatusMsg

// .duckcdp.StatusMsgSrc src = 1;
inline void StatusMsg::clear_src() {
  _impl_.src_ = 0;
}
inline ::duckcdp::StatusMsgSrc StatusMsg::_internal_src() const {
  return static_cast< ::duckcdp::StatusMsgSrc >(_impl_.src_);
}
inline ::duckcdp::StatusMsgSrc StatusMsg::src() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusMsg.src)
  return _internal_src();
}
inline void StatusMsg::_internal_set_src(::duckcdp::StatusMsgSrc value) {
  
  _impl_.src_ = value;
}
inline void StatusMsg::set_src(::duckcdp::StatusMsgSrc value) {
  _internal_set_src(value);
  // @@protoc_insertion_point(field_set:duckcdp.StatusMsg.src)
}

// string urgency = 2;
inline void StatusMsg::clear_urgency() {
  _impl_.urgency_.ClearToEmpty();
}
inline const std::string& StatusMsg::urgency() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusMsg.urgency)
  return _internal_urgency();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StatusMsg::set_urgency(ArgT0&& arg0, ArgT... args) {
 
 _impl_.urgency_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:duckcdp.StatusMsg.urgency)
}
inline std::string* StatusMsg::mutable_urgency() {
  std::string* _s = _internal_mutable_urgency();
  // @@protoc_insertion_point(field_mutable:duckcdp.StatusMsg.urgency)
  return _s;
}
inline const std::string& StatusMsg::_internal_urgency() const {
  return _impl_.urgency_.Get();
}
inline void StatusMsg::_internal_set_urgency(const std::string& value) {
  
  _impl_.urgency_.Set(value, GetArenaForAllocation());
}
inline std::string* StatusMsg::_internal_mutable_urgency() {
  
  return _impl_.urgency_.Mutable(GetArenaForAllocation());
}
inline std::string* StatusMsg::release_urgency() {
  // @@protoc_insertion_point(field_release:duckcdp.StatusMsg.urgency)
  return _impl_.urgency_.Release();
}
inline void StatusMsg::set_allocated_urgency(std::string* urgency) {
  if (urgency != nullptr) {
    
  } else {
    
  }
  _impl_.urgency_.SetAllocated(urgency, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.urgency_.IsDefault()) {
    _impl_.urgency_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:duckcdp.StatusMsg.urgency)
}

// bool has_gps = 3;
inline void StatusMsg::clear_has_gps() {
  _impl_.has_gps_ = false;
}
inline bool StatusMsg::_internal_has_gps() const {
  return _impl_.has_gps_;
}
inline bool StatusMsg::has_gps() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusMsg.has_gps)
  return _internal_has_gps();
}
inline void StatusMsg::_internal_set_has_gps(bool value) {
  
  _impl_.has_gps_ = value;
}
inline void StatusMsg::set_has_gps(bool value) {
  _internal_set_has_gps(value);
  // @@protoc_insertion_point(field_set:duckcdp.StatusMsg.has_gps)
}

// sint32 lat_e7 = 4;
inline void StatusMsg::clear_lat_e7() {
  _impl_.lat_e7_ = 0;
}
inline int32_t StatusMsg::_internal_lat_e7() const {
  return _impl_.lat_e7_;
}
inline int32_t StatusMsg::lat_e7() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusMsg.lat_e7)
  return _internal_lat_e7();
}
inline void StatusMsg::_internal_set_lat_e7(int32_t value) {
  
  _impl_.lat_e7_ = value;
}
inline void StatusMsg::set_lat_e7(int32_t value) {
  _internal_set_lat_e7(value);
  // @@protoc_insertion_point(field_set:duckcdp.StatusMsg.lat_e7)
}

// sint32 lng_e7 = 5;
inline void StatusMsg::clear_lng_e7() {
  _impl_.lng_e7_ = 0;
}
inline int32_t StatusMsg::_internal_lng_e7() const {
  return _impl_.lng_e7_;
}
inline int32_t StatusMsg::lng_e7() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusMsg.lng_e7)
  return _internal_lng_e7();
}
inline void StatusMsg::_internal_set_lng_e7(int32_t value) {
  
  _impl_.lng_e7_ = value;
}
inline void StatusMsg::set_lng_e7(int32_t value) {
  _internal_set_lng_e7(value);
  // @@protoc_insertion_point(field_set:duckcdp.StatusMsg.lng_e7)
}

// string text = 6;
inline void StatusMsg::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& StatusMsg::text() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusMsg.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StatusMsg::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:duckcdp.StatusMsg.text)
}
inline std::string* StatusMsg::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:duckcdp.StatusMsg.text)
  return _s;
}
inline const std::string& StatusMsg::_internal_text() const {
  return _impl_.text_.Get();
}
inline void StatusMsg::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* StatusMsg::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* StatusMsg::release_text() {
  // @@protoc_insertion_point(field_release:duckcdp.StatusMsg.text)
  return _impl_.text_.Release();
}
inline void StatusMsg::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:duckcdp.StatusMsg.text)
}

// -------------------------------------------------------------------

// StatusReport

// .duckcdp.SosAlert sos = 1;
inline bool StatusReport::_internal_has_sos() const {
  return report_case() == kSos;
}
inline bool StatusReport::has_sos() const {
  return _internal_has_sos();
}
inline void StatusReport::set_has_sos() {
  _impl_._oneof_case_[0] = kSos;
}
inline void StatusReport::clear_sos() {
  if (_internal_has_sos()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.report_.sos_;
    }
    clear_has_report();
  }
}
inline ::duckcdp::SosAlert* StatusReport::release_sos() {
  // @@protoc_insertion_point(field_release:duckcdp.StatusReport.sos)
  if (_internal_has_sos()) {
    clear_has_report();
    ::duckcdp::SosAlert* temp = _impl_.report_.sos_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.report_.sos_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::duckcdp::SosAlert& StatusReport::_internal_sos() const {
  return _internal_has_sos()
      ? *_impl_.report_.sos_
      : reinterpret_cast< ::duckcdp::SosAlert&>(::duckcdp::_SosAlert_default_instance_);
}
inline const ::duckcdp::SosAlert& StatusReport::sos() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusReport.sos)
  return _internal_sos();
}
inline ::duckcdp::SosAlert* StatusReport::unsafe_arena_release_sos() {
  // @@protoc_insertion_point(field_unsafe_arena_release:duckcdp.StatusReport.sos)
  if (_internal_has_sos()) {
    clear_has_report();
    ::duckcdp::SosAlert* temp = _impl_.report_.sos_;
    _impl_.report_.sos_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void StatusReport::unsafe_arena_set_allocated_sos(::duckcdp::SosAlert* sos) {
  clear_report();
  if (sos) {
    set_has_sos();
    _impl_.report_.sos_ = sos;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:duckcdp.StatusReport.sos)
}
inline ::duckcdp::SosAlert* StatusReport::_internal_mutable_sos() {
  if (!_internal_has_sos()) {
    clear_report();
    set_has_sos();
    _impl_.report_.sos_ = CreateMaybeMessage< ::duckcdp::SosAlert >(GetArenaForAllocation());
  }
  return _impl_.report_.sos_;
}
inline ::duckcdp::SosAlert* StatusReport::mutable_sos() {
  ::duckcdp::SosAlert* _msg = _internal_mutable_sos();
  // @@protoc_insertion_point(field_mutable:duckcdp.StatusReport.sos)
  return _msg;
}

// .duckcdp.StatusMsg msg = 2;
inline bool StatusReport::_internal_has_msg() const {
  return report_case() == kMsg;
}
inline bool StatusReport::has_msg() const {
  return _internal_has_msg();
}
inline void StatusReport::set_has_msg() {
  _impl_._oneof_case_[0] = kMsg;
}
inline void StatusReport::clear_msg() {
  if (_internal_has_msg()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.report_.msg_;
    }
    clear_has_report();
  }
}
inline ::duckcdp::StatusMsg* StatusReport::release_msg() {
  // @@protoc_insertion_point(field_release:duckcdp.StatusReport.msg)
  if (_internal_has_msg()) {
    clear_has_report();
    ::duckcdp::StatusMsg* temp = _impl_.report_.msg_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.report_.msg_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::duckcdp::StatusMsg& StatusReport::_internal_msg() const {
  return _internal_has_msg()
      ? *_impl_.report_.msg_
      : reinterpret_cast< ::duckcdp::StatusMsg&>(::duckcdp::_StatusMsg_default_instance_);
}
inline const ::duckcdp::StatusMsg& StatusReport::msg() const {
  // @@protoc_insertion_point(field_get:duckcdp.StatusReport.msg)
  return _internal_msg();
}
inline ::duckcdp::StatusMsg* StatusReport::unsafe_arena_release_msg() {
  // @@protoc_insertion_point(field_unsafe_arena_release:duckcdp.StatusReport.msg)
  if (_internal_has_msg()) {
    clear_has_report();
    ::duckcdp::StatusMsg* temp = _impl_.report_.msg_;
    _impl_.report_.msg_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void StatusReport::unsafe_arena_set_allocated_msg(::duckcdp::StatusMsg* msg) {
  clear_report();
  if (msg) {
    set_has_msg();
    _impl_.report_.msg_ = msg;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:duckcdp.StatusReport.msg)
}
inline ::duckcdp::StatusMsg* StatusReport::_internal_mutable_msg() {
  if (!_internal_has_msg()) {
    clear_report();
    set_has_msg();
    _impl_.report_.msg_ = CreateMaybeMessage< ::duckcdp::StatusMsg >(GetArenaForAllocation());
  }
  return _impl_.report_.msg_;
}
inline ::duckcdp::StatusMsg* StatusReport::mutable_msg() {
  ::duckcdp::StatusMsg* _msg = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:duckcdp.StatusReport.msg)
  return _msg;
}

inline bool StatusReport::has_report() const {
  return report_case() != REPORT_NOT_SET;
}
inline void StatusReport::clear_has_report() {
  _impl_._oneof_case_[0] = REPORT_NOT_SET;
}
inline StatusReport::ReportCase StatusReport::report_case() const {
  return StatusReport::ReportCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// OpText

// string text = 1;
inline void OpText::clear_text() {
  _impl_.text_.ClearToEmpty();
}
inline const std::string& OpText::text() const {
  // @@protoc_insertion_point(field_get:duckcdp.OpText.text)
  return _internal_text();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OpText::set_text(ArgT0&& arg0, ArgT... args) {
 
 _impl_.text_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:duckcdp.OpText.text)
}
inline std::string* OpText::mutable_text() {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:duckcdp.OpText.text)
  return _s;
}
inline const std::string& OpText::_internal_text() const {
  return _impl_.text_.Get();
}
inline void OpText::_internal_set_text(const std::string& value) {
  
  _impl_.text_.Set(value, GetArenaForAllocation());
}
inline std::string* OpText::_internal_mutable_text() {
  
  return _impl_.text_.Mutable(GetArenaForAllocation());
}
inline std::string* OpText::release_text() {
  // @@protoc_insertion_point(field_release:duckcdp.OpText.text)
  return _impl_.text_.Release();
}
inline void OpText::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  _impl_.text_.SetAllocated(text, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:duckcdp.OpText.text)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace duckcdp

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::duckcdp::GpsSource> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::duckcdp::GpsSource>() {
  return ::duckcdp::GpsSource_descriptor();
}
template <> struct is_proto_enum< ::duckcdp::GpsNoFixReason> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::duckcdp::GpsNoFixReason>() {
  return ::duckcdp::GpsNoFixReason_descriptor();
}
template <> struct is_proto_enum< ::duckcdp::SosOrigin> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::duckcdp::SosOrigin>() {
  return ::duckcdp::SosOrigin_descriptor();
}
template <> struct is_proto_enum< ::duckcdp::MTalkKind> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::duckcdp::MTalkKind>() {
  return ::duckcdp::MTalkKind_descriptor();
}
template <> struct is_proto_enum< ::duckcdp::StatusMsgSrc> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::duckcdp::StatusMsgSrc>() {
  return ::duckcdp::StatusMsgSrc_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_duck_5fpayloads_2eproto
