// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: duck_payloads.proto

#include "duck_payloads.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace duckcdp {
PROTOBUF_CONSTEXPR GpsReading::GpsReading(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.has_fix_)*/false
  , /*decltype(_impl_.source_)*/0
  , /*decltype(_impl_.no_fix_reason_)*/0
  , /*decltype(_impl_.lat_e7_)*/0
  , /*decltype(_impl_.lng_e7_)*/0
  , /*decltype(_impl_.alt_m_)*/0
  , /*decltype(_impl_.spd_dkmh_)*/0u
  , /*decltype(_impl_.hdg_deg_)*/0u
  , /*decltype(_impl_.sats_)*/0u
  , /*decltype(_impl_.batt_pct_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GpsReadingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GpsReadingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GpsReadingDefaultTypeInternal() {}
  union {
    GpsReading _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GpsReadingDefaultTypeInternal _GpsReading_default_instance_;
PROTOBUF_CONSTEXPR SosAlert::SosAlert(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.origin_)*/0
  , /*decltype(_impl_.gps_source_)*/0
  , /*decltype(_impl_.has_gps_)*/false
  , /*decltype(_impl_.lat_e7_)*/0
  , /*decltype(_impl_.lng_e7_)*/0
  , /*decltype(_impl_.alt_m_)*/0
  , /*decltype(_impl_.spd_dkmh_)*/0u
  , /*decltype(_impl_.hdg_deg_)*/0u
  , /*decltype(_impl_.batt_pct_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SosAlertDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SosAlertDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SosAlertDefaultTypeInternal() {}
  union {
    SosAlert _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SosAlertDefaultTypeInternal _SosAlert_default_instance_;
PROTOBUF_CONSTEXPR HealthStatus::HealthStatus(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.counter_)*/0u
  , /*decltype(_impl_.free_memory_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HealthStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthStatusDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthStatusDefaultTypeInternal() {}
  union {
    HealthStatus _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthStatusDefaultTypeInternal _HealthStatus_default_instance_;
PROTOBUF_CONSTEXPR MTalk::MTalk(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.kind_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MTalkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MTalkDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MTalkDefaultTypeInternal() {}
  union {
    MTalk _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MTalkDefaultTypeInternal _MTalk_default_instance_;
PROTOBUF_CONSTEXPR StatusMsg::StatusMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.urgency_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.src_)*/0
  , /*decltype(_impl_.has_gps_)*/false
  , /*decltype(_impl_.lat_e7_)*/0
  , /*decltype(_impl_.lng_e7_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StatusMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusMsgDefaultTypeInternal() {}
  union {
    StatusMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusMsgDefaultTypeInternal _StatusMsg_default_instance_;
PROTOBUF_CONSTEXPR StatusReport::StatusReport(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.report_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct StatusReportDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusReportDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusReportDefaultTypeInternal() {}
  union {
    StatusReport _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusReportDefaultTypeInternal _StatusReport_default_instance_;
PROTOBUF_CONSTEXPR OpText::OpText(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OpTextDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OpTextDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OpTextDefaultTypeInternal() {}
  union {
    OpText _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OpTextDefaultTypeInternal _OpText_default_instance_;
}  // namespace duckcdp
static ::_pb::Metadata file_level_metadata_duck_5fpayloads_2eproto[7];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_duck_5fpayloads_2eproto[5];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_duck_5fpayloads_2eproto = nullptr;

const uint32_t TableStruct_duck_5fpayloads_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.has_fix_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.source_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.no_fix_reason_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.lat_e7_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.lng_e7_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.alt_m_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.spd_dkmh_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.hdg_deg_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.sats_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::GpsReading, _impl_.batt_pct_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.origin_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.gps_source_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.has_gps_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.lat_e7_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.lng_e7_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.alt_m_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.spd_dkmh_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.hdg_deg_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::SosAlert, _impl_.batt_pct_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::duckcdp::HealthStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::duckcdp::HealthStatus, _impl_.counter_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::HealthStatus, _impl_.free_memory_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::duckcdp::MTalk, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::duckcdp::MTalk, _impl_.kind_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::MTalk, _impl_.mid_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::MTalk, _impl_.text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusMsg, _impl_.src_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusMsg, _impl_.urgency_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusMsg, _impl_.has_gps_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusMsg, _impl_.lat_e7_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusMsg, _impl_.lng_e7_),
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusMsg, _impl_.text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusReport, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusReport, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::duckcdp::StatusReport, _impl_.report_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::duckcdp::OpText, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::duckcdp::OpText, _impl_.text_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::duckcdp::GpsReading)},
  { 16, -1, -1, sizeof(::duckcdp::SosAlert)},
  { 31, -1, -1, sizeof(::duckcdp::HealthStatus)},
  { 39, -1, -1, sizeof(::duckcdp::MTalk)},
  { 48, -1, -1, sizeof(::duckcdp::StatusMsg)},
  { 60, -1, -1, sizeof(::duckcdp::StatusReport)},
  { 69, -1, -1, sizeof(::duckcdp::OpText)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::duckcdp::_GpsReading_default_instance_._instance,
  &::duckcdp::_SosAlert_default_instance_._instance,
  &::duckcdp::_HealthStatus_default_instance_._instance,
  &::duckcdp::_MTalk_default_instance_._instance,
  &::duckcdp::_StatusMsg_default_instance_._instance,
  &::duckcdp::_StatusReport_default_instance_._instance,
  &::duckcdp::_OpText_default_instance_._instance,
};

const char descriptor_table_protodef_duck_5fpayloads_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023duck_payloads.proto\022\007duckcdp\"\343\001\n\nGpsRe"
  "ading\022\017\n\007has_fix\030\001 \001(\010\022\"\n\006source\030\002 \001(\0162\022"
  ".duckcdp.GpsSource\022.\n\rno_fix_reason\030\003 \001("
  "\0162\027.duckcdp.GpsNoFixReason\022\016\n\006lat_e7\030\004 \001"
  "(\021\022\016\n\006lng_e7\030\005 \001(\021\022\r\n\005alt_m\030\006 \001(\021\022\020\n\010spd"
  "_dkmh\030\007 \001(\r\022\017\n\007hdg_deg\030\010 \001(\r\022\014\n\004sats\030\t \001"
  "(\r\022\020\n\010batt_pct\030\n \001(\r\"\313\001\n\010SosAlert\022\"\n\006ori"
  "gin\030\001 \001(\0162\022.duckcdp.SosOrigin\022&\n\ngps_sou"
  "rce\030\002 \001(\0162\022.duckcdp.GpsSource\022\017\n\007has_gps"
  "\030\003 \001(\010\022\016\n\006lat_e7\030\004 \001(\021\022\016\n\006lng_e7\030\005 \001(\021\022\r"
  "\n\005alt_m\030\006 \001(\021\022\020\n\010spd_dkmh\030\007 \001(\r\022\017\n\007hdg_d"
  "eg\030\010 \001(\r\022\020\n\010batt_pct\030\t \001(\r\"4\n\014HealthStat"
  "us\022\017\n\007counter\030\001 \001(\r\022\023\n\013free_memory\030\002 \001(\005"
  "\"D\n\005MTalk\022 \n\004kind\030\001 \001(\0162\022.duckcdp.MTalkK"
  "ind\022\013\n\003mid\030\002 \001(\t\022\014\n\004text\030\003 \001(\t\"\177\n\tStatus"
  "Msg\022\"\n\003src\030\001 \001(\0162\025.duckcdp.StatusMsgSrc\022"
  "\017\n\007urgency\030\002 \001(\t\022\017\n\007has_gps\030\003 \001(\010\022\016\n\006lat"
  "_e7\030\004 \001(\021\022\016\n\006lng_e7\030\005 \001(\021\022\014\n\004text\030\006 \001(\t\""
  "]\n\014StatusReport\022 \n\003sos\030\001 \001(\0132\021.duckcdp.S"
  "osAlertH\000\022!\n\003msg\030\002 \001(\0132\022.duckcdp.StatusM"
  "sgH\000B\010\n\006report\"\026\n\006OpText\022\014\n\004text\030\001 \001(\t*M"
  "\n\tGpsSource\022\023\n\017GPS_SOURCE_NONE\020\000\022\025\n\021GPS_"
  "SOURCE_DEVICE\020\001\022\024\n\020GPS_SOURCE_PHONE\020\002*[\n"
  "\016GpsNoFixReason\022\023\n\017GPS_REASON_NONE\020\000\022\030\n\024"
  "GPS_REASON_NO_SIGNAL\020\001\022\032\n\026GPS_REASON_NO_"
  "RESPONSE\020\002*P\n\tSosOrigin\022\026\n\022SOS_ORIGIN_UN"
  "KNOWN\020\000\022\025\n\021SOS_ORIGIN_DEVICE\020\001\022\024\n\020SOS_OR"
  "IGIN_PHONE\020\002*)\n\tMTalkKind\022\r\n\tMTALK_MSG\020\000"
  "\022\r\n\tMTALK_ACK\020\001*_\n\014StatusMsgSrc\022\032\n\026STATU"
  "S_MSG_SRC_UNKNOWN\020\000\022\030\n\024STATUS_MSG_SRC_PH"
  "ONE\020\001\022\031\n\025STATUS_MSG_SRC_DEVICE\020\002b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_duck_5fpayloads_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_duck_5fpayloads_2eproto = {
    false, false, 1240, descriptor_table_protodef_duck_5fpayloads_2eproto,
    "duck_payloads.proto",
    &descriptor_table_duck_5fpayloads_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_duck_5fpayloads_2eproto::offsets,
    file_level_metadata_duck_5fpayloads_2eproto, file_level_enum_descriptors_duck_5fpayloads_2eproto,
    file_level_service_descriptors_duck_5fpayloads_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_duck_5fpayloads_2eproto_getter() {
  return &descriptor_table_duck_5fpayloads_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_duck_5fpayloads_2eproto(&descriptor_table_duck_5fpayloads_2eproto);
namespace duckcdp {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GpsSource_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_duck_5fpayloads_2eproto);
  return file_level_enum_descriptors_duck_5fpayloads_2eproto[0];
}
bool GpsSource_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GpsNoFixReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_duck_5fpayloads_2eproto);
  return file_level_enum_descriptors_duck_5fpayloads_2eproto[1];
}
bool GpsNoFixReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SosOrigin_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_duck_5fpayloads_2eproto);
  return file_level_enum_descriptors_duck_5fpayloads_2eproto[2];
}
bool SosOrigin_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MTalkKind_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_duck_5fpayloads_2eproto);
  return file_level_enum_descriptors_duck_5fpayloads_2eproto[3];
}
bool MTalkKind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StatusMsgSrc_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_duck_5fpayloads_2eproto);
  return file_level_enum_descriptors_duck_5fpayloads_2eproto[4];
}
bool StatusMsgSrc_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class GpsReading::_Internal {
 public:
};

GpsReading::GpsReading(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:duckcdp.GpsReading)
}
GpsReading::GpsReading(const GpsReading& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GpsReading* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.has_fix_){}
    , decltype(_impl_.source_){}
    , decltype(_impl_.no_fix_reason_){}
    , decltype(_impl_.lat_e7_){}
    , decltype(_impl_.lng_e7_){}
    , decltype(_impl_.alt_m_){}
    , decltype(_impl_.spd_dkmh_){}
    , decltype(_impl_.hdg_deg_){}
    , decltype(_impl_.sats_){}
    , decltype(_impl_.batt_pct_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.has_fix_, &from._impl_.has_fix_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.batt_pct_) -
    reinterpret_cast<char*>(&_impl_.has_fix_)) + sizeof(_impl_.batt_pct_));
  // @@protoc_insertion_point(copy_constructor:duckcdp.GpsReading)
}

inline void GpsReading::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.has_fix_){false}
    , decltype(_impl_.source_){0}
    , decltype(_impl_.no_fix_reason_){0}
    , decltype(_impl_.lat_e7_){0}
    , decltype(_impl_.lng_e7_){0}
    , decltype(_impl_.alt_m_){0}
    , decltype(_impl_.spd_dkmh_){0u}
    , decltype(_impl_.hdg_deg_){0u}
    , decltype(_impl_.sats_){0u}
    , decltype(_impl_.batt_pct_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GpsReading::~GpsReading() {
  // @@protoc_insertion_point(destructor:duckcdp.GpsReading)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GpsReading::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GpsReading::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GpsReading::Clear() {
// @@protoc_insertion_point(message_clear_start:duckcdp.GpsReading)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.has_fix_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.batt_pct_) -
      reinterpret_cast<char*>(&_impl_.has_fix_)) + sizeof(_impl_.batt_pct_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GpsReading::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool has_fix = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.has_fix_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .duckcdp.GpsSource source = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_source(static_cast<::duckcdp::GpsSource>(val));
        } else
          goto handle_unusual;
        continue;
      // .duckcdp.GpsNoFixReason no_fix_reason = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_no_fix_reason(static_cast<::duckcdp::GpsNoFixReason>(val));
        } else
          goto handle_unusual;
        continue;
      // sint32 lat_e7 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.lat_e7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 lng_e7 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.lng_e7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 alt_m = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.alt_m_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 spd_dkmh = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.spd_dkmh_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 hdg_deg = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.hdg_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 sats = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.sats_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 batt_pct = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.batt_pct_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GpsReading::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:duckcdp.GpsReading)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool has_fix = 1;
  if (this->_internal_has_fix() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_has_fix(), target);
  }

  // .duckcdp.GpsSource source = 2;
  if (this->_internal_source() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_source(), target);
  }

  // .duckcdp.GpsNoFixReason no_fix_reason = 3;
  if (this->_internal_no_fix_reason() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_no_fix_reason(), target);
  }

  // sint32 lat_e7 = 4;
  if (this->_internal_lat_e7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(4, this->_internal_lat_e7(), target);
  }

  // sint32 lng_e7 = 5;
  if (this->_internal_lng_e7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(5, this->_internal_lng_e7(), target);
  }

  // sint32 alt_m = 6;
  if (this->_internal_alt_m() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(6, this->_internal_alt_m(), target);
  }

  // uint32 spd_dkmh = 7;
  if (this->_internal_spd_dkmh() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_spd_dkmh(), target);
  }

  // uint32 hdg_deg = 8;
  if (this->_internal_hdg_deg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_hdg_deg(), target);
  }

  // uint32 sats = 9;
  if (this->_internal_sats() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_sats(), target);
  }

  // uint32 batt_pct = 10;
  if (this->_internal_batt_pct() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(10, this->_internal_batt_pct(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:duckcdp.GpsReading)
  return target;
}

size_t GpsReading::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:duckcdp.GpsReading)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool has_fix = 1;
  if (this->_internal_has_fix() != 0) {
    total_size += 1 + 1;
  }

  // .duckcdp.GpsSource source = 2;
  if (this->_internal_source() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_source());
  }

  // .duckcdp.GpsNoFixReason no_fix_reason = 3;
  if (this->_internal_no_fix_reason() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_no_fix_reason());
  }

  // sint32 lat_e7 = 4;
  if (this->_internal_lat_e7() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_lat_e7());
  }

  // sint32 lng_e7 = 5;
  if (this->_internal_lng_e7() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_lng_e7());
  }

  // sint32 alt_m = 6;
  if (this->_internal_alt_m() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_alt_m());
  }

  // uint32 spd_dkmh = 7;
  if (this->_internal_spd_dkmh() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_spd_dkmh());
  }

  // uint32 hdg_deg = 8;
  if (this->_internal_hdg_deg() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_hdg_deg());
  }

  // uint32 sats = 9;
  if (this->_internal_sats() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_sats());
  }

  // uint32 batt_pct = 10;
  if (this->_internal_batt_pct() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_batt_pct());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GpsReading::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GpsReading::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GpsReading::GetClassData() const { return &_class_data_; }


void GpsReading::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GpsReading*>(&to_msg);
  auto& from = static_cast<const GpsReading&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:duckcdp.GpsReading)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_fix() != 0) {
    _this->_internal_set_has_fix(from._internal_has_fix());
  }
  if (from._internal_source() != 0) {
    _this->_internal_set_source(from._internal_source());
  }
  if (from._internal_no_fix_reason() != 0) {
    _this->_internal_set_no_fix_reason(from._internal_no_fix_reason());
  }
  if (from._internal_lat_e7() != 0) {
    _this->_internal_set_lat_e7(from._internal_lat_e7());
  }
  if (from._internal_lng_e7() != 0) {
    _this->_internal_set_lng_e7(from._internal_lng_e7());
  }
  if (from._internal_alt_m() != 0) {
    _this->_internal_set_alt_m(from._internal_alt_m());
  }
  if (from._internal_spd_dkmh() != 0) {
    _this->_internal_set_spd_dkmh(from._internal_spd_dkmh());
  }
  if (from._internal_hdg_deg() != 0) {
    _this->_internal_set_hdg_deg(from._internal_hdg_deg());
  }
  if (from._internal_sats() != 0) {
    _this->_internal_set_sats(from._internal_sats());
  }
  if (from._internal_batt_pct() != 0) {
    _this->_internal_set_batt_pct(from._internal_batt_pct());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GpsReading::CopyFrom(const GpsReading& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:duckcdp.GpsReading)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GpsReading::IsInitialized() const {
  return true;
}

void GpsReading::InternalSwap(GpsReading* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GpsReading, _impl_.batt_pct_)
      + sizeof(GpsReading::_impl_.batt_pct_)
      - PROTOBUF_FIELD_OFFSET(GpsReading, _impl_.has_fix_)>(
          reinterpret_cast<char*>(&_impl_.has_fix_),
          reinterpret_cast<char*>(&other->_impl_.has_fix_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GpsReading::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_duck_5fpayloads_2eproto_getter, &descriptor_table_duck_5fpayloads_2eproto_once,
      file_level_metadata_duck_5fpayloads_2eproto[0]);
}

// ===================================================================

class SosAlert::_Internal {
 public:
};

SosAlert::SosAlert(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:duckcdp.SosAlert)
}
SosAlert::SosAlert(const SosAlert& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SosAlert* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.origin_){}
    , decltype(_impl_.gps_source_){}
    , decltype(_impl_.has_gps_){}
    , decltype(_impl_.lat_e7_){}
    , decltype(_impl_.lng_e7_){}
    , decltype(_impl_.alt_m_){}
    , decltype(_impl_.spd_dkmh_){}
    , decltype(_impl_.hdg_deg_){}
    , decltype(_impl_.batt_pct_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.origin_, &from._impl_.origin_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.batt_pct_) -
    reinterpret_cast<char*>(&_impl_.origin_)) + sizeof(_impl_.batt_pct_));
  // @@protoc_insertion_point(copy_constructor:duckcdp.SosAlert)
}

inline void SosAlert::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.origin_){0}
    , decltype(_impl_.gps_source_){0}
    , decltype(_impl_.has_gps_){false}
    , decltype(_impl_.lat_e7_){0}
    , decltype(_impl_.lng_e7_){0}
    , decltype(_impl_.alt_m_){0}
    , decltype(_impl_.spd_dkmh_){0u}
    , decltype(_impl_.hdg_deg_){0u}
    , decltype(_impl_.batt_pct_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SosAlert::~SosAlert() {
  // @@protoc_insertion_point(destructor:duckcdp.SosAlert)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SosAlert::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SosAlert::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SosAlert::Clear() {
// @@protoc_insertion_point(message_clear_start:duckcdp.SosAlert)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.origin_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.batt_pct_) -
      reinterpret_cast<char*>(&_impl_.origin_)) + sizeof(_impl_.batt_pct_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SosAlert::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .duckcdp.SosOrigin origin = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_origin(static_cast<::duckcdp::SosOrigin>(val));
        } else
          goto handle_unusual;
        continue;
      // .duckcdp.GpsSource gps_source = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_gps_source(static_cast<::duckcdp::GpsSource>(val));
        } else
          goto handle_unusual;
        continue;
      // bool has_gps = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.has_gps_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 lat_e7 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.lat_e7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 lng_e7 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.lng_e7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 alt_m = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.alt_m_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 spd_dkmh = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.spd_dkmh_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 hdg_deg = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.hdg_deg_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 batt_pct = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.batt_pct_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SosAlert::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:duckcdp.SosAlert)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .duckcdp.SosOrigin origin = 1;
  if (this->_internal_origin() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_origin(), target);
  }

  // .duckcdp.GpsSource gps_source = 2;
  if (this->_internal_gps_source() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_gps_source(), target);
  }

  // bool has_gps = 3;
  if (this->_internal_has_gps() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_has_gps(), target);
  }

  // sint32 lat_e7 = 4;
  if (this->_internal_lat_e7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(4, this->_internal_lat_e7(), target);
  }

  // sint32 lng_e7 = 5;
  if (this->_internal_lng_e7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(5, this->_internal_lng_e7(), target);
  }

  // sint32 alt_m = 6;
  if (this->_internal_alt_m() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(6, this->_internal_alt_m(), target);
  }

  // uint32 spd_dkmh = 7;
  if (this->_internal_spd_dkmh() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_spd_dkmh(), target);
  }

  // uint32 hdg_deg = 8;
  if (this->_internal_hdg_deg() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(8, this->_internal_hdg_deg(), target);
  }

  // uint32 batt_pct = 9;
  if (this->_internal_batt_pct() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(9, this->_internal_batt_pct(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:duckcdp.SosAlert)
  return target;
}

size_t SosAlert::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:duckcdp.SosAlert)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .duckcdp.SosOrigin origin = 1;
  if (this->_internal_origin() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_origin());
  }

  // .duckcdp.GpsSource gps_source = 2;
  if (this->_internal_gps_source() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_gps_source());
  }

  // bool has_gps = 3;
  if (this->_internal_has_gps() != 0) {
    total_size += 1 + 1;
  }

  // sint32 lat_e7 = 4;
  if (this->_internal_lat_e7() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_lat_e7());
  }

  // sint32 lng_e7 = 5;
  if (this->_internal_lng_e7() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_lng_e7());
  }

  // sint32 alt_m = 6;
  if (this->_internal_alt_m() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_alt_m());
  }

  // uint32 spd_dkmh = 7;
  if (this->_internal_spd_dkmh() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_spd_dkmh());
  }

  // uint32 hdg_deg = 8;
  if (this->_internal_hdg_deg() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_hdg_deg());
  }

  // uint32 batt_pct = 9;
  if (this->_internal_batt_pct() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_batt_pct());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SosAlert::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SosAlert::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SosAlert::GetClassData() const { return &_class_data_; }


void SosAlert::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SosAlert*>(&to_msg);
  auto& from = static_cast<const SosAlert&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:duckcdp.SosAlert)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_origin() != 0) {
    _this->_internal_set_origin(from._internal_origin());
  }
  if (from._internal_gps_source() != 0) {
    _this->_internal_set_gps_source(from._internal_gps_source());
  }
  if (from._internal_has_gps() != 0) {
    _this->_internal_set_has_gps(from._internal_has_gps());
  }
  if (from._internal_lat_e7() != 0) {
    _this->_internal_set_lat_e7(from._internal_lat_e7());
  }
  if (from._internal_lng_e7() != 0) {
    _this->_internal_set_lng_e7(from._internal_lng_e7());
  }
  if (from._internal_alt_m() != 0) {
    _this->_internal_set_alt_m(from._internal_alt_m());
  }
  if (from._internal_spd_dkmh() != 0) {
    _this->_internal_set_spd_dkmh(from._internal_spd_dkmh());
  }
  if (from._internal_hdg_deg() != 0) {
    _this->_internal_set_hdg_deg(from._internal_hdg_deg());
  }
  if (from._internal_batt_pct() != 0) {
    _this->_internal_set_batt_pct(from._internal_batt_pct());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SosAlert::CopyFrom(const SosAlert& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:duckcdp.SosAlert)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SosAlert::IsInitialized() const {
  return true;
}

void SosAlert::InternalSwap(SosAlert* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SosAlert, _impl_.batt_pct_)
      + sizeof(SosAlert::_impl_.batt_pct_)
      - PROTOBUF_FIELD_OFFSET(SosAlert, _impl_.origin_)>(
          reinterpret_cast<char*>(&_impl_.origin_),
          reinterpret_cast<char*>(&other->_impl_.origin_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SosAlert::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_duck_5fpayloads_2eproto_getter, &descriptor_table_duck_5fpayloads_2eproto_once,
      file_level_metadata_duck_5fpayloads_2eproto[1]);
}

// ===================================================================

class HealthStatus::_Internal {
 public:
};

HealthStatus::HealthStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:duckcdp.HealthStatus)
}
HealthStatus::HealthStatus(const HealthStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HealthStatus* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.counter_){}
    , decltype(_impl_.free_memory_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.counter_, &from._impl_.counter_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.free_memory_) -
    reinterpret_cast<char*>(&_impl_.counter_)) + sizeof(_impl_.free_memory_));
  // @@protoc_insertion_point(copy_constructor:duckcdp.HealthStatus)
}

inline void HealthStatus::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.counter_){0u}
    , decltype(_impl_.free_memory_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HealthStatus::~HealthStatus() {
  // @@protoc_insertion_point(destructor:duckcdp.HealthStatus)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HealthStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HealthStatus::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HealthStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:duckcdp.HealthStatus)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.counter_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.free_memory_) -
      reinterpret_cast<char*>(&_impl_.counter_)) + sizeof(_impl_.free_memory_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HealthStatus::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 counter = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.counter_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 free_memory = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.free_memory_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HealthStatus::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:duckcdp.HealthStatus)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 counter = 1;
  if (this->_internal_counter() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_counter(), target);
  }

  // int32 free_memory = 2;
  if (this->_internal_free_memory() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_free_memory(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:duckcdp.HealthStatus)
  return target;
}

size_t HealthStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:duckcdp.HealthStatus)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 counter = 1;
  if (this->_internal_counter() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_counter());
  }

  // int32 free_memory = 2;
  if (this->_internal_free_memory() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_free_memory());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HealthStatus::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HealthStatus::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HealthStatus::GetClassData() const { return &_class_data_; }


void HealthStatus::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HealthStatus*>(&to_msg);
  auto& from = static_cast<const HealthStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:duckcdp.HealthStatus)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_counter() != 0) {
    _this->_internal_set_counter(from._internal_counter());
  }
  if (from._internal_free_memory() != 0) {
    _this->_internal_set_free_memory(from._internal_free_memory());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HealthStatus::CopyFrom(const HealthStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:duckcdp.HealthStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HealthStatus::IsInitialized() const {
  return true;
}

void HealthStatus::InternalSwap(HealthStatus* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HealthStatus, _impl_.free_memory_)
      + sizeof(HealthStatus::_impl_.free_memory_)
      - PROTOBUF_FIELD_OFFSET(HealthStatus, _impl_.counter_)>(
          reinterpret_cast<char*>(&_impl_.counter_),
          reinterpret_cast<char*>(&other->_impl_.counter_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HealthStatus::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_duck_5fpayloads_2eproto_getter, &descriptor_table_duck_5fpayloads_2eproto_once,
      file_level_metadata_duck_5fpayloads_2eproto[2]);
}

// ===================================================================

class MTalk::_Internal {
 public:
};

MTalk::MTalk(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:duckcdp.MTalk)
}
MTalk::MTalk(const MTalk& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MTalk* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mid_){}
    , decltype(_impl_.text_){}
    , decltype(_impl_.kind_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.mid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mid().empty()) {
    _this->_impl_.mid_.Set(from._internal_mid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.kind_ = from._impl_.kind_;
  // @@protoc_insertion_point(copy_constructor:duckcdp.MTalk)
}

inline void MTalk::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mid_){}
    , decltype(_impl_.text_){}
    , decltype(_impl_.kind_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.mid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

MTalk::~MTalk() {
  // @@protoc_insertion_point(destructor:duckcdp.MTalk)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MTalk::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.mid_.Destroy();
  _impl_.text_.Destroy();
}

void MTalk::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MTalk::Clear() {
// @@protoc_insertion_point(message_clear_start:duckcdp.MTalk)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mid_.ClearToEmpty();
  _impl_.text_.ClearToEmpty();
  _impl_.kind_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MTalk::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .duckcdp.MTalkKind kind = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_kind(static_cast<::duckcdp::MTalkKind>(val));
        } else
          goto handle_unusual;
        continue;
      // string mid = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_mid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "duckcdp.MTalk.mid"));
        } else
          goto handle_unusual;
        continue;
      // string text = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "duckcdp.MTalk.text"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MTalk::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:duckcdp.MTalk)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .duckcdp.MTalkKind kind = 1;
  if (this->_internal_kind() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_kind(), target);
  }

  // string mid = 2;
  if (!this->_internal_mid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mid().data(), static_cast<int>(this->_internal_mid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "duckcdp.MTalk.mid");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_mid(), target);
  }

  // string text = 3;
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "duckcdp.MTalk.text");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:duckcdp.MTalk)
  return target;
}

size_t MTalk::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:duckcdp.MTalk)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string mid = 2;
  if (!this->_internal_mid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mid());
  }

  // string text = 3;
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  // .duckcdp.MTalkKind kind = 1;
  if (this->_internal_kind() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_kind());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MTalk::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MTalk::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MTalk::GetClassData() const { return &_class_data_; }


void MTalk::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MTalk*>(&to_msg);
  auto& from = static_cast<const MTalk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:duckcdp.MTalk)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_mid().empty()) {
    _this->_internal_set_mid(from._internal_mid());
  }
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (from._internal_kind() != 0) {
    _this->_internal_set_kind(from._internal_kind());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MTalk::CopyFrom(const MTalk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:duckcdp.MTalk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MTalk::IsInitialized() const {
  return true;
}

void MTalk::InternalSwap(MTalk* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.mid_, lhs_arena,
      &other->_impl_.mid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
  swap(_impl_.kind_, other->_impl_.kind_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MTalk::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_duck_5fpayloads_2eproto_getter, &descriptor_table_duck_5fpayloads_2eproto_once,
      file_level_metadata_duck_5fpayloads_2eproto[3]);
}

// ===================================================================

class StatusMsg::_Internal {
 public:
};

StatusMsg::StatusMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:duckcdp.StatusMsg)
}
StatusMsg::StatusMsg(const StatusMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StatusMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.urgency_){}
    , decltype(_impl_.text_){}
    , decltype(_impl_.src_){}
    , decltype(_impl_.has_gps_){}
    , decltype(_impl_.lat_e7_){}
    , decltype(_impl_.lng_e7_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.urgency_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.urgency_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_urgency().empty()) {
    _this->_impl_.urgency_.Set(from._internal_urgency(), 
      _this->GetArenaForAllocation());
  }
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.src_, &from._impl_.src_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.lng_e7_) -
    reinterpret_cast<char*>(&_impl_.src_)) + sizeof(_impl_.lng_e7_));
  // @@protoc_insertion_point(copy_constructor:duckcdp.StatusMsg)
}

inline void StatusMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.urgency_){}
    , decltype(_impl_.text_){}
    , decltype(_impl_.src_){0}
    , decltype(_impl_.has_gps_){false}
    , decltype(_impl_.lat_e7_){0}
    , decltype(_impl_.lng_e7_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.urgency_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.urgency_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

StatusMsg::~StatusMsg() {
  // @@protoc_insertion_point(destructor:duckcdp.StatusMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StatusMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.urgency_.Destroy();
  _impl_.text_.Destroy();
}

void StatusMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StatusMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:duckcdp.StatusMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.urgency_.ClearToEmpty();
  _impl_.text_.ClearToEmpty();
  ::memset(&_impl_.src_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.lng_e7_) -
      reinterpret_cast<char*>(&_impl_.src_)) + sizeof(_impl_.lng_e7_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StatusMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .duckcdp.StatusMsgSrc src = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_src(static_cast<::duckcdp::StatusMsgSrc>(val));
        } else
          goto handle_unusual;
        continue;
      // string urgency = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_urgency();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "duckcdp.StatusMsg.urgency"));
        } else
          goto handle_unusual;
        continue;
      // bool has_gps = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.has_gps_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 lat_e7 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.lat_e7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // sint32 lng_e7 = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.lng_e7_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string text = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "duckcdp.StatusMsg.text"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StatusMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:duckcdp.StatusMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .duckcdp.StatusMsgSrc src = 1;
  if (this->_internal_src() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_src(), target);
  }

  // string urgency = 2;
  if (!this->_internal_urgency().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_urgency().data(), static_cast<int>(this->_internal_urgency().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "duckcdp.StatusMsg.urgency");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_urgency(), target);
  }

  // bool has_gps = 3;
  if (this->_internal_has_gps() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_has_gps(), target);
  }

  // sint32 lat_e7 = 4;
  if (this->_internal_lat_e7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(4, this->_internal_lat_e7(), target);
  }

  // sint32 lng_e7 = 5;
  if (this->_internal_lng_e7() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(5, this->_internal_lng_e7(), target);
  }

  // string text = 6;
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "duckcdp.StatusMsg.text");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:duckcdp.StatusMsg)
  return target;
}

size_t StatusMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:duckcdp.StatusMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string urgency = 2;
  if (!this->_internal_urgency().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_urgency());
  }

  // string text = 6;
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  // .duckcdp.StatusMsgSrc src = 1;
  if (this->_internal_src() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_src());
  }

  // bool has_gps = 3;
  if (this->_internal_has_gps() != 0) {
    total_size += 1 + 1;
  }

  // sint32 lat_e7 = 4;
  if (this->_internal_lat_e7() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_lat_e7());
  }

  // sint32 lng_e7 = 5;
  if (this->_internal_lng_e7() != 0) {
    total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(this->_internal_lng_e7());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StatusMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StatusMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StatusMsg::GetClassData() const { return &_class_data_; }


void StatusMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StatusMsg*>(&to_msg);
  auto& from = static_cast<const StatusMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:duckcdp.StatusMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_urgency().empty()) {
    _this->_internal_set_urgency(from._internal_urgency());
  }
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (from._internal_src() != 0) {
    _this->_internal_set_src(from._internal_src());
  }
  if (from._internal_has_gps() != 0) {
    _this->_internal_set_has_gps(from._internal_has_gps());
  }
  if (from._internal_lat_e7() != 0) {
    _this->_internal_set_lat_e7(from._internal_lat_e7());
  }
  if (from._internal_lng_e7() != 0) {
    _this->_internal_set_lng_e7(from._internal_lng_e7());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StatusMsg::CopyFrom(const StatusMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:duckcdp.StatusMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatusMsg::IsInitialized() const {
  return true;
}

void StatusMsg::InternalSwap(StatusMsg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.urgency_, lhs_arena,
      &other->_impl_.urgency_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StatusMsg, _impl_.lng_e7_)
      + sizeof(StatusMsg::_impl_.lng_e7_)
      - PROTOBUF_FIELD_OFFSET(StatusMsg, _impl_.src_)>(
          reinterpret_cast<char*>(&_impl_.src_),
          reinterpret_cast<char*>(&other->_impl_.src_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StatusMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_duck_5fpayloads_2eproto_getter, &descriptor_table_duck_5fpayloads_2eproto_once,
      file_level_metadata_duck_5fpayloads_2eproto[4]);
}

// ===================================================================

class StatusReport::_Internal {
 public:
  static const ::duckcdp::SosAlert& sos(const StatusReport* msg);
  static const ::duckcdp::StatusMsg& msg(const StatusReport* msg);
};

const ::duckcdp::SosAlert&
StatusReport::_Internal::sos(const StatusReport* msg) {
  return *msg->_impl_.report_.sos_;
}
const ::duckcdp::StatusMsg&
StatusReport::_Internal::msg(const StatusReport* msg) {
  return *msg->_impl_.report_.msg_;
}
void StatusReport::set_allocated_sos(::duckcdp::SosAlert* sos) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_report();
  if (sos) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(sos);
    if (message_arena != submessage_arena) {
      sos = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sos, submessage_arena);
    }
    set_has_sos();
    _impl_.report_.sos_ = sos;
  }
  // @@protoc_insertion_point(field_set_allocated:duckcdp.StatusReport.sos)
}
void StatusReport::set_allocated_msg(::duckcdp::StatusMsg* msg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_report();
  if (msg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(msg);
    if (message_arena != submessage_arena) {
      msg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, msg, submessage_arena);
    }
    set_has_msg();
    _impl_.report_.msg_ = msg;
  }
  // @@protoc_insertion_point(field_set_allocated:duckcdp.StatusReport.msg)
}
StatusReport::StatusReport(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:duckcdp.StatusReport)
}
StatusReport::StatusReport(const StatusReport& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StatusReport* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.report_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_report();
  switch (from.report_case()) {
    case kSos: {
      _this->_internal_mutable_sos()->::duckcdp::SosAlert::MergeFrom(
          from._internal_sos());
      break;
    }
    case kMsg: {
      _this->_internal_mutable_msg()->::duckcdp::StatusMsg::MergeFrom(
          from._internal_msg());
      break;
    }
    case REPORT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:duckcdp.StatusReport)
}

inline void StatusReport::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.report_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_report();
}

StatusReport::~StatusReport() {
  // @@protoc_insertion_point(destructor:duckcdp.StatusReport)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StatusReport::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_report()) {
    clear_report();
  }
}

void StatusReport::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StatusReport::clear_report() {
// @@protoc_insertion_point(one_of_clear_start:duckcdp.StatusReport)
  switch (report_case()) {
    case kSos: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.report_.sos_;
      }
      break;
    }
    case kMsg: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.report_.msg_;
      }
      break;
    }
    case REPORT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = REPORT_NOT_SET;
}


void StatusReport::Clear() {
// @@protoc_insertion_point(message_clear_start:duckcdp.StatusReport)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_report();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StatusReport::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .duckcdp.SosAlert sos = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_sos(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .duckcdp.StatusMsg msg = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_msg(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StatusReport::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:duckcdp.StatusReport)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .duckcdp.SosAlert sos = 1;
  if (_internal_has_sos()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::sos(this),
        _Internal::sos(this).GetCachedSize(), target, stream);
  }

  // .duckcdp.StatusMsg msg = 2;
  if (_internal_has_msg()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::msg(this),
        _Internal::msg(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:duckcdp.StatusReport)
  return target;
}

size_t StatusReport::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:duckcdp.StatusReport)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (report_case()) {
    // .duckcdp.SosAlert sos = 1;
    case kSos: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.report_.sos_);
      break;
    }
    // .duckcdp.StatusMsg msg = 2;
    case kMsg: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.report_.msg_);
      break;
    }
    case REPORT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StatusReport::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StatusReport::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StatusReport::GetClassData() const { return &_class_data_; }


void StatusReport::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StatusReport*>(&to_msg);
  auto& from = static_cast<const StatusReport&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:duckcdp.StatusReport)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.report_case()) {
    case kSos: {
      _this->_internal_mutable_sos()->::duckcdp::SosAlert::MergeFrom(
          from._internal_sos());
      break;
    }
    case kMsg: {
      _this->_internal_mutable_msg()->::duckcdp::StatusMsg::MergeFrom(
          from._internal_msg());
      break;
    }
    case REPORT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StatusReport::CopyFrom(const StatusReport& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:duckcdp.StatusReport)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StatusReport::IsInitialized() const {
  return true;
}

void StatusReport::InternalSwap(StatusReport* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.report_, other->_impl_.report_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata StatusReport::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_duck_5fpayloads_2eproto_getter, &descriptor_table_duck_5fpayloads_2eproto_once,
      file_level_metadata_duck_5fpayloads_2eproto[5]);
}

// ===================================================================

class OpText::_Internal {
 public:
};

OpText::OpText(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:duckcdp.OpText)
}
OpText::OpText(const OpText& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OpText* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.text_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:duckcdp.OpText)
}

inline void OpText::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.text_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OpText::~OpText() {
  // @@protoc_insertion_point(destructor:duckcdp.OpText)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OpText::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.text_.Destroy();
}

void OpText::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OpText::Clear() {
// @@protoc_insertion_point(message_clear_start:duckcdp.OpText)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OpText::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string text = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "duckcdp.OpText.text"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OpText::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:duckcdp.OpText)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string text = 1;
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "duckcdp.OpText.text");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_text(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:duckcdp.OpText)
  return target;
}

size_t OpText::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:duckcdp.OpText)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string text = 1;
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OpText::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OpText::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OpText::GetClassData() const { return &_class_data_; }


void OpText::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OpText*>(&to_msg);
  auto& from = static_cast<const OpText&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:duckcdp.OpText)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OpText::CopyFrom(const OpText& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:duckcdp.OpText)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OpText::IsInitialized() const {
  return true;
}

void OpText::InternalSwap(OpText* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata OpText::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_duck_5fpayloads_2eproto_getter, &descriptor_table_duck_5fpayloads_2eproto_once,
      file_level_metadata_duck_5fpayloads_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace duckcdp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::duckcdp::GpsReading*
Arena::CreateMaybeMessage< ::duckcdp::GpsReading >(Arena* arena) {
  return Arena::CreateMessageInternal< ::duckcdp::GpsReading >(arena);
}
template<> PROTOBUF_NOINLINE ::duckcdp::SosAlert*
Arena::CreateMaybeMessage< ::duckcdp::SosAlert >(Arena* arena) {
  return Arena::CreateMessageInternal< ::duckcdp::SosAlert >(arena);
}
template<> PROTOBUF_NOINLINE ::duckcdp::HealthStatus*
Arena::CreateMaybeMessage< ::duckcdp::HealthStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::duckcdp::HealthStatus >(arena);
}
template<> PROTOBUF_NOINLINE ::duckcdp::MTalk*
Arena::CreateMaybeMessage< ::duckcdp::MTalk >(Arena* arena) {
  return Arena::CreateMessageInternal< ::duckcdp::MTalk >(arena);
}
template<> PROTOBUF_NOINLINE ::duckcdp::StatusMsg*
Arena::CreateMaybeMessage< ::duckcdp::StatusMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::duckcdp::StatusMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::duckcdp::StatusReport*
Arena::CreateMaybeMessage< ::duckcdp::StatusReport >(Arena* arena) {
  return Arena::CreateMessageInternal< ::duckcdp::StatusReport >(arena);
}
template<> PROTOBUF_NOINLINE ::duckcdp::OpText*
Arena::CreateMaybeMessage< ::duckcdp::OpText >(Arena* arena) {
  return Arena::CreateMessageInternal< ::duckcdp::OpText >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
